### ISSUE TITLE
Support Java8 Date / Time

### ISSUE THREAD

**Issue by vaesbart** [Ninja-Squad/DbSetup#51]
Hi,

any info on supporting Java 8 new java.time classes ?

Thanks - and thanks for this project !

Greetings,
Bart.

**Comment by jnizet** [comment]
Hi. Thanks for your interest.

I haven't taken the time to work on this yet. I won't be able to do it for the next few weeks (I'll be on holiday, scuba-diving \o/), but I'll try doing it when I come back.

**Comment by jnizet** [comment]
Hi @vaesbart.

I have implemented support for java.time classes in #52. It would be nice if you could tell me if the changes would suit your needs, and provide feedback on the changes.
It would be even nicer if you could build the topic/java8 branch and test it on your project. If you can't, I'll release a 2.0.0-beta version later, that will be available in Maven central so that you can test, and send issues or RFEs before the final 2.0.0 release.
