### ISSUE TITLE
Support ignoring commit option on DbSetup#launch

### ISSUE THREAD

**Issue by kazuki43zoo** [Ninja-Squad/DbSetup#61]
I'm considering to use the `DbSetup` on [the Spring TestContext Framework](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#testcontext-framework). However the `DbSetup#launch` method always commit a local transaction. In this implementation, (probably) i cannot use [the transaction management functionality](http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#testcontext-tx) provided by the Spring TestContext Framework.
Therefore i hope to add a new option that ignore commit operation on `DbSetup` class.
What do you think ?

**Comment by jnizet** [comment]
Hi @kazuki43zoo and thanks for the interest.

There shouldn't be any problem using Spring and DbSetup together. DbSetup will populate your database, then your test will start another transaction and do whatever it needs to do with the data in the database. Since DbSetup commits its transaction before the test transaction starts, there shouldn't be any problem. 

Do you have a concrete scenario or use-case where DbSetup committing is a problem?

**Comment by kazuki43zoo** [comment]
Hi @jnizet , Sorry for late reply.

In my projects, there are cases that database is used sharing by multiple developers. In this case, test data setup operations(insert, update, delete) and updating operations under testing has need to isolate with other transaction basically(as possible as). Also we need to rollback to status that before executing unit tests.

In order to satisfy this requirement, i use a transaction management functionality provided by spring test. We can rollback easily to status that before executing unit tests using a transaction management functionality provided by spring test. (Note that: test for REQUIRES_NEW is exclude)


Therefore i hope to add a new option that ignore commit operation on DbSetup class for executing setup operation and test within same transaction.

What do you think ?

**Comment by jnizet** [comment]
Not committing the transaction wouldn't be sufficient. DbSetup would also need to hook into Spring Transaction management to use the same connection as the one Spring is using. That could probably be done by creating a custom Destination implementation. This Destination could also return a Connection proxy that would do nothing when commit() is called. But I don't plan to make DbSetup dependant on Spring, and I think your use-case shouldn't be promoted. In my optinion, sharing a database between developers for tests is a bad idea. Not committing test transactions is a bad idea. Excluding certain use-cases because they need a new transaction is a bad idea.

But as I said, you should be able to hack a Destination implementation to support your setup, if you really want to.
